name: push
on: push
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Test mypcb
        run: make check; make clean
  test-distrib:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Test mypcb distrib
        run: make dist; make distclean
  build:
    needs: test-distrib
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          gcc --version