# This is for testing only, the binary won't run on macOS as it is not signed.
name: macos-release
on: push
env:
  version: 3.3.6
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Test mypcb
        run: make check; make clean
  test-distrib:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Test mypcb distrib
        run: make dist; make distclean
#  build:
#    needs: test-distrib
#    runs-on: macos-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v4
#      - name: build
#        run: |
#          make prefix=/opt/mypcb sysconfdir=/opt/mypcb/etc outputdir=/opt/mypcb/out all
#          cd src
#          tar -czf mypcb-macos-arm-${{ env.version }}.tar.gz mypcb
#      - name: release
#        uses: softprops/action-gh-release@v2
#        with:
#          token: ${{ secrets.DEVOPS_TOKEN }}
#          tag_name: ${{ env.version }}
#          name: release ${{ env.version }}
#          files: src/mypcb-macos-arm-${{ env.version }}.tar.gz